### PR TITLE
lint: ESLint support + lint squishing

### PR DESCRIPTION
**Pull request by KerfuffleV2**
Definitely didn't intend to do this but I could not stop playing lint whack-a-mole.

The changes are extensive, but most of them were pretty mechanical. The lint support part could be split out into a separate PR easily.

The main interesting change is the `Valuable` class I added for dealing with "truthy" values. I'm actually impressed with the stuff you can do with TypeScript's type system.

All tests still pass and the extension appears to work. This will need considerably more work before it could become a real pull request.

### CODE REVIEW

**Review by josh-berry — COMMENTED** [review]
OK, so I've gone through this whole PR (and made a bunch of comments), and at this stage, I'm somewhat skeptical, but I'm willing to keep going and see what else we find.

At the end of the day, this exercise DID find a couple small bugs (noted below), and there might be more to be found.

However, I'm not sure it would have helped with #241 in the moment; I can easily imagine that I would have mindlessly written `if (yes(...))` instead of `if (...)`, and the linter would have been happy but the bug would be the same--there's no substitute for being mindful of what you're writing. Indeed, a couple of the aforementioned bugs are good examples--the linter pointed to the problem, but shutting the linter up didn't lead to the actual fix.

My main concern centers around the fact that we've added a bunch of new code to do nothing more than replicate behavior outlawed by the linter, and I want to be mindful of verbosity/readability/linter-induced awkwardness. For example, transforming `if (foo)` into `if (Valuable.yes(foo))` might be reassuring to the linter, but it doesn't add much meaning for humans beyond "yes, I really intended to write this" (even if it's wrong).

That said, I do like the fact that it was finding and pointing out unnecessary things in the code (casts, regex escaping, etc.), and I certainly see the value in it pointing to pre-existing bugs and giving more early feedback about things that might be wrong.

Net: I think if we can keep the verbosity of any linter-required changes down and make sure code stays focused on intention rather than mechanics, the linter is probably a good trade-off.

**Comment by KerfuffleV2** [comment]
@josh-berry I really have to apologize for wasting your time here, this shouldn't have been submitted even as a draft. I don't want to just delete it now that you spent so much time carefully reviewing the changes (and I did read all your comments.) I really wasn't trying to get you to exhaustively review the changes in this state!

You definitely had some legitimate criticisms about the `Valuable` stuff. The biggest problem here is that I can make exchanges that preserve the existing semantics of the code (hopefully) but a lot of the time I don't really understand the full context of what it's supposed to be doing, so any existing bugs would just get passed along.

I think you're right to be skeptical. What do you think about just closing this and I will submit another PR that just enables running `npm run lint` / `make lint`? (It seems like this will involve some package versions being updated.)

Of course if you think there would be a benefit in me responding to your individual comments or making changes to the existing PR, I'd be willing to do so. I could also try to extract specific types of changes from this set.

**Comment by josh-berry** [comment]
> @josh-berry I really have to apologize for wasting your time here, this shouldn't have been submitted even as a draft. I don't want to just delete it now that you spent so much time carefully reviewing the changes (and I did read all your comments.) I really wasn't trying to get you to exhaustively review the changes in this state!

No worries, it's actually my fault--I didn't realize until about 2/3rds of the way through that it had been marked as a draft! 🤦 

> You definitely had some legitimate criticisms about the `Valuable` stuff. The biggest problem here is that I can make exchanges that preserve the existing semantics of the code (hopefully) but a lot of the time I don't really understand the full context of what it's supposed to be doing, so any existing bugs would just get passed along.

Yeah, that's fair.

> I think you're right to be skeptical. What do you think about just closing this and I will submit another PR that just enables running `npm run lint` / `make lint`? (It seems like this will involve some package versions being updated.)

Seems reasonable. There are a couple maybe-bugs there we should actually fix, so maybe those could go as one PR and the linting change could go as another PR, and then we iron out the linting over time? I don't necessarily want you to throw away the work you've done, either!

> Of course if you think there would be a benefit in me responding to your individual comments or making changes to the existing PR, I'd be willing to do so. I could also try to extract specific types of changes from this set.

The good thing about having done this exercise is that there are two things we should almost certainly fix (tagged in my comments above):
* `await cursor.delete()`
* Better hygiene around `undefined` vs `''` for bookmark IDs (you found a few places which you `yes()`ified bookmark-ID checks, but these are probably better-handled with `=== undefined`)

Also, we've learned at least one surprising thing that will affect the linter rules, which is that treating `(...)!` as a lint is probably not a good idea (there's often not a good fix that doesn't impose an unnecessary runtime cost).

**Comment by josh-berry** [comment]
> > I don't necessarily want you to throw away the work you've done, either!
> 
> At this point, I'm not too confident a lot of it has any practical value. I'm okay with it hibernating indefinitely in a closed PR — the changes would still be available there if they're ever relevant/useful.

Sounds good.

> > `await cursor.delete()`
> 
> You're talking about `cursor.delete()` specifically, not generally futures that weren't `await`ed. Correct?

Yes.

> > Better hygiene around `undefined` vs `''` for bookmark IDs
> 
> Those ids really confused the linter due to the type union thing you have. It thinks they are objects and can therefore never be falsey. If you're sure there's nothing that actually depends on them being falsey like a string then always comparing with `undefined` makes sense. I didn't do that when I was making those changes since I didn't know if anything actually depended on those semantics.

Ohh, because they are `string | number` in some places (bookmark vs. tab), I guess. I don't think there is anything that depends on those semantics specifically (at least, I hope not), but I can double-check. It's kind of an academic issue anyway since I've never seen FF give me a bookmark ID which is an empty string.

**Comment by josh-berry** [comment]
Gonna close this because I ended up reformatting the whole codebase with Prettier. It's, well, uglier in a number of cases, but it means nobody has to think about "proper" formatting anymore.

**Pull request closed without merging**
