### PR TITLE
change thickness of container color

### PR DESCRIPTION
**Pull request by acress1**
Hi
In my opinion, the color of the container bar was not thick enough to be distinguished quickly.
Don't hesitate to change the values if needed :)
thx!

### CODE REVIEW

**Review by josh-berry — COMMENTED** [review]
Thanks, I'm happy to merge this, but would you mind pulling this variable out of the dark/light themes and moving it into `metrics/normal.less`? That will avoid duplicating it between dark/light themes, which wouldn't be necessary anymore.

**Comment by acress1** [comment]
Ok, consider it done. However, can you confirm I need to completely remove the --container-indicator-shadow-style:” line in the dark and light files ?

**Comment by josh-berry** [comment]
Yep that's correct. Thanks!

**Comment by acress1** [comment]
@josh-berry great, that's done. The PR should be correct now. :)

**Comment by josh-berry** [comment]
Thank you!

**Pull request merged**
